### ISSUE TITLE
Update to express 4, add utf-8 charset where we set the content type

### ISSUE THREAD

**Issue by mwoc** [papandreou/express-compiless#9]
Express 4 sets the charset in the Content-Type header to utf-8. For consistency, we should do the same. See also lib/compiless.less:64 - where we do toString('utf-8')

@papandreou I have some commits lying ready, could I push them here or do you prefer a pull request?

**Comment by gustavnikolaj** [comment]
ping @mwoc :-)

**Comment by gustavnikolaj** [comment]
Express was updated in the meantime :-)
